export const LABELS = {
  HOME: 'Home',
  MENU: 'Menu',
  ABOUT_US: 'About Us',
  CONTACT_US: 'Contact Us',
  ORDER_NOW: 'Order Now',
  SEND_MESSAGE: 'Send Message',
  MYKOPIKO: 'Mykopiko',
  POPULAR_MENU: 'Popular Menu',
  FRAPPE_MENU: 'Frappe Menu',
  ESPRESSO_MENU: 'Espresso Menu',
  PASTRIES_MENU: 'Pastries Menu',
  QUICK_LINKS: 'Quick links',
  VISIT_US: 'Visit Us',
  ADDRESS_CITY: 'Manila Bulacan City',
  HOURS_WEEKDAY: 'Mon – Fri 9AM – 10PM',
  HOURS_WEEKEND: 'Sat – Sun 8AM – 6PM',
  PRIVACY: 'Privacy',
  TERMS_OF_USE: 'Terms of Use',
  PRIVACY_POLICY: 'Privacy Policy',
  COOKIES: 'Cookies',
  CALL_US: 'Call Us',
  PHONE_1: '123-456-789-10',
  PHONE_2: '097-531-295-19',
  WHY_CHOOSE_US: 'Why Choose Us',
  CUSTOMER_REVIEWS: 'What our customers say',
  SEND_US_MESSAGE: 'Send us a message',
  YOUR_CART: 'Your Cart',
  CLOSE: 'Close',
  CHECKOUT: 'Checkout',
  INFORMATION: 'Information',
  PAYMENT: 'Payment',
  CONFIRM: 'Confirm',
  CUSTOMER_INFORMATION: 'Customer Information',
  FULL_NAME: 'Full name',
  EMAIL_ADDRESS: 'Email Address',
  DELIVERY_ADDRESS: 'Delivery Address',
  PHONE_NUMBER: 'Phone Number',
  ORDER_SUMMARY: 'Order Summary',
  SUBTOTAL: 'Subtotal',
  DELIVERY: 'Delivery',
  TOTAL: 'Total',
  CONFIRM_ORDER: 'Confirm Order',
  BACK: 'Back',
  REFERENCE_NUMBER: 'Reference number',
  CONFIRM_PAYMENT: 'Confirm Payment',
  TRACK_ORDER: 'Track Order',
  BACK_HOME: 'Back Home',
  CALL_RIDER: 'Call rider',
  ORDER_RECEIPT: 'Order Receipt',
  REQUIRED_FIELD: 'is required',
  PROCESSING: 'Processing...',
  TRACK_ORDER_HEADER: 'Track Your Order',
  EMPTY_TRACK_TITLE: 'There’s no order to track.',
  EMPTY_TRACK_MSG: 'Kindly place an order first.',
  BROWSE_MENU: 'Browse Menu',
  FEE: 'Fee',
  VIEW_CART: 'View cart',
  LOGOUT: 'Logout',
  PROFILE: 'Profile',
  SOCIAL_MEDIA: 'Social Media',
};
