export const LABELS = {
    labels: {
        HOME: 'Home',
        MENU: 'Menu',
        ABOUT_US: 'About Us',
        CONTACT_US: 'Contact Us',
        ORDER_NOW: 'Order Now',
        SEND_MESSAGE: 'Send Message',
        MYKOPIKO: 'Mykopiko',
        POPULAR_MENU: 'Popular Menu',
        FRAPPE_MENU: 'frappe Menu',
        ESPRESSO_MENU: 'espresso Menu',
        PASTRIES_MENU: 'pastries Menu',
        QUICK_LINKS: 'Quick links',
        VISIT_US: 'Visit Us',
        ADDRESS_CITY: 'Manila Bulacan City',
        HOURS_WEEKDAY: 'Mon – Fri 9AM – 10PM',
        HOURS_WEEKEND: 'Sat – Sun 8AM – 6PM',
        PRIVACY: 'PRIVACY',
        TERMS_OF_USE: 'Terms of Use',
        PRIVACY_POLICY: 'Privacy Policy',
        COOKIES: 'Cookies',
        CALL_US: 'CALL US',
        PHONE_1: '123-456-789-10',
        PHONE_2: '097-531-295-19',
        WHY_CHOOSE_US: 'Why choose Us',
        CUSTOMER_REVIEWS: 'What our customers say',
        SEND_US_MESSAGE: 'Send us a message',
        YOUR_CART: 'Your Cart',
        CLOSE: 'Close',
        CHECKOUT: 'checkout',
        INFORMATION: 'Information',
        PAYMENT: 'Payment',
        CONFIRM: 'Confirm',
        CUSTOMER_INFORMATION: 'Customer Information',
        FULL_NAME: 'Full name',
        EMAIL_ADDRESS: 'Email Address',
        DELIVERY_ADDRESS: 'Delivery Address',
        PHONE_NUMBER: 'Phone Number',
        ORDER_SUMMARY: 'Order Summary',
        SUBTOTAL: 'Subtotal',
        DELIVERY: 'Delivery',
        TOTAL: 'TOTAL',
        CONFIRM_ORDER: 'Confirm Order',
        BACK: 'Back',
        REFERENCE_NUMBER: 'Reference number',
        CONFIRM_PAYMENT: 'Confirm Payment',
        TRACK_ORDER: 'Track Order',
        BACK_HOME: 'Back home',
        CALL_RIDER: 'Call rider',
        ORDER_RECEIPT: 'Order reciept'
    }
};
